'use strict'

// common adverbs
// this list could be large (eg. 100~1000)
// but I don't think it needs to be "huge": some adverbs are not interesting
// for our most common use cases.. unless I'm wrong of course!
// (eg. "ambisyllabically", "aneurysmally".. )
//
// note: we also need to detect negative adverbs "eg. unlikely" means there is
// no event
const en = [
  "wisely",
  "slowly",
  "quickly",
  "eventuall?y",
  "accidentall?y",
  "accidently",
  "actively",
  "incidentall?y",
  "recently",
  "adequately",
  "admirably",
  "firmly",
  "arbitrarily",
  "apparently",
  "arguably",
  "nearly",
  "barely",
  "controversiall?y",
  "apologeticall?y",
  "weirdly",
  "astonishingly",
  "astoundingly",
  "awfully",
  "awkwardly",
  "strangely",
  "automaticall?y",
  "basically",
  "(?:most )?likely",
  "(?:most )?probably",
  "very likely",
  "soon",
  "recently",
  "barely",
  "deeply",
  "lightly",
  "bestiall?y",
  "insanely",
  "beautifull?y",
  "modestly",
  "boldly",
  "broadly",
  "completely",
  "brutall?y",
  "brusquely",
  "bruskly",
  "bullishly",
  "bearly",
  "capriciou?sly",
  "carefully",
  "carelessly",
  "discree?tly",
  "casuall?y",
  "categoricall?y",
  "catastrophicall?y",
  "by chance",
  "by (?:pure )?luck",
  "randomly",
  "by accident",
  "fortuitously",
  "ceremoniously",
  "formall?y",
  "finall?y",
  "temporary",
  "temporarill?y"
]

const fr = [
  "sagement",
  "progressivement",
  "lentement",
  "rapidement",
  "complètement",
  "bizarrement",
  "étonamm?ent",
  "étrangement",
  "curieusement",
  "récemment",
  "silencieusement",
  "subitement",
  "dernièrement",
  "activement",
  "arbitrairement",
  "apparemm?ent",
  "probablement",
  "vraisemblablement",
  "manifestement",
  "de toute évidence",
  "visiblement",
  "pratiquement",
  "de justesse",
  "prochainement",
  "dernièrement",
  "à peine",
  "profondément",
  "légèrement",
  "superficiell?ement",
  "sauvagement",
  "superbement",
  "modestement",
  "pompeusement",
  "largement",
  "complètement",
  "brutalement",
  "brusquement",
  "précautionn?eusement",
  "discrètement",
  "nonchalamm?ent",
  "catégoriquement",
  "catastrophiquement",
  "par chance",
  "par hasard",
  "par accident",
  "fortuitement",
  "formell?ement",
  "finalement",
  "brièvement",
  "temporairement"
]

module.exports = en.concat(fr)
